# Generated by Django 5.1.1 on 2024-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0002_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=500)),
                ('p_description', models.TextField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_stock_quantity', models.IntegerField()),
                ('p_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
