# Generated by Django 5.1.1 on 2024-10-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0005_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
