# Generated by Django 5.1.1 on 2024-10-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0007_user1model_productuser1model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuser1model',
            old_name='userp',
            new_name='usern',
        ),
    ]
