# Generated by Django 5.1.1 on 2024-10-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0013_hotel_bookins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookins',
            new_name='Booking',
        ),
    ]
