# Generated by Django 5.1.1 on 2024-11-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0020_userimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
