# Generated by Django 5.1.1 on 2024-11-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0021_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
